spring:

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console   # http://localhost:8080/h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  # SQL 초기화 설정
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql  # 테스트 데이터 로드용

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL   # null 값 제외
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.conduit: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always